### ISSUE TITLE
Support Resource Pack

### ISSUE THREAD

**Issue by Snowiiii** [Snowiiii/Pumpkin#10]
Add support for sending an Resource Pack to the Client. Specified via the Config, including its Sha1 hash.
Reference: https://wiki.vg/Protocol#Add_Resource_Pack_.28configuration.29

**Comment by neeleshpoli** [comment]
Hey! Looking through the code, it seems like resource pack support is already implemented. Is there some reason why this issue was reopened and went from done back to todo?

**Comment by Snowiiii** [comment]
> Hey! Looking through the code, it seems like resource pack support is already implemented. Is there some reason why this issue was reopened and went from done back to todo?

Hey, It should be working but the last time i tested it did not. I was doing other stuff and did not test furhter. I will try to test and may fix this today

**Comment by Snowiiii** [comment]
Okay its fixed and works. We just currently don't wait/get the response. There is also the Resourcepack Packets at Play state which we currently don't use
