### ISSUE TITLE
Wrong packet fields

### ISSUE THREAD

**Issue by Alvsch** [Snowiiii/Pumpkin#108]
- [x] I've searched existing issues and couldn't find a duplicate.

**Describe the bug**
The struct "SLoginPluginResponse" has wrong fields.
When the packet is deserialized we first read if the "successful" field is true, meaning that there will be more data. But we also treat the data as a Option, leading to the first byte of data being lost.

**Expected behavior**
The "successful" field should be removed and data.is_some() should be used instead.

**Additional context**
https://wiki.vg/Protocol#Login_Plugin_Response
this was confusing and hard to debug

**Comment by Snowiiii** [comment]
Yep, I see already had this issue in the past. Wiki.vg sometimes makes it hard to difference between an Optional and an boolean above
