### ISSUE TITLE
Documentation is unclear. Stuck on Quick Start

### ISSUE THREAD

**Issue by bbstilson** [Snowiiii/Pumpkin#114]
- [X] I've searched existing issues and couldn't find a duplicate.

Hello there. I am not experienced in running a Minecraft server, but I wanted to try out Pumpkin. Unfortunately, I am stuck on the [Quick Start](https://snowiiii.github.io/Pumpkin/about/quick-start.html) guide. Specifically:

> You can place a vanilla world into the Pumpkin/ directory when you want. Just name the World to `world`

I am not sure what this means. I made a directory called world in the git root (`Pumpkin/`), but the server fails to start with:

```
➜ Pumpkin (master) ✔ cargo run --release
    Finished `release` profile [optimized + debuginfo] target(s) in 0.33s
     Running `target/release/pumpkin`
2024-10-12T21:22:28.106Z INFO  [pumpkin::server@main] Loading Plugins
thread 'main' panicked at pumpkin-world/src/level.rs:112:13:
World region folder does not exist, despite there being a root folder.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

I assume I need to do more than just `mkdir world`, but I'm not sure what that is. I am able to start the server without creating that directory, but the client fails to connect even though an attempt seems to have been made:

```
2024-10-12T21:20:44.818Z INFO  [pumpkin@main] Accepted connection from: 127.0.0.1:37296
[pumpkin/src/client/client_packet.rs:37:9] "handshake" = "handshake"
[pumpkin/src/client/client_packet.rs:62:9] "ping" = "ping"
```

I'd be happy to update the Quick Start guide in a PR if someone is able to help a noob understand what one should do 🙁 

Thanks!

**Comment by Bryntet** [comment]
Sounds like you just put a folder named world there instead of putting a world that you'd like to play there with the name world

**Comment by Snowiiii** [comment]
It says "place a vanilla world" in "Pumpkin/" named "world". An empty folder is not a vanilla world, So it does not work

**Comment by lukas0008** [comment]
If i remember correctly, you need world/ folder and world/region/ folder.

**Comment by Snowiiii** [comment]
> If i remember correctly, you need world/ folder and world/region/ folder.

ye, thats what a vanilla world also usually has

**Comment by gurkleffe** [comment]
You can get a world folder from your Minecraft save files. Some sites also offer pregenerated/built worlds.
