### ISSUE TITLE
Missing "Custom Auth support" in Features(WIP)

### ISSUE THREAD

**Issue by Z-fentom** [Snowiiii/Pumpkin#121]
![image](https://github.com/user-attachments/assets/bb79baf5-11bd-4110-ad9a-15e64df27639)
Missing part where it says that it supports custom auth :+1:

**Comment by Snowiiii** [comment]
Hey, Im not sure if this is so important enough. This feature list only covers the most important things so most things are not listed

**Comment by Z-fentom** [comment]
> Hey, Im not sure if this is so important enough. This feature list only covers the most important things so most things are not listed

Yea i just wanted to point it out :)
