### ISSUE TITLE
[docs] Missing logo and favicon in the Vitepress docs

### ISSUE THREAD

**Issue by reynaldichernando** [Snowiiii/Pumpkin#122]
- [x] I've searched existing issues and couldn't find a duplicate.

**Describe the bug**
The logo in the top left corner of the page is missing/broken, along with the site favicon.
<img width="664" alt="image" src="https://github.com/user-attachments/assets/f05ba9c9-4f9d-4708-9fed-c36a95f633b6">

<img width="188" alt="image" src="https://github.com/user-attachments/assets/78859c75-d4bc-4488-9be4-6ac4a4d743ad">

**To Reproduce**
1. Open https://snowiiii.github.io/Pumpkin/

**Expected behavior**
It should show the respective logo and favicon.

**Environment (please complete the following information):**

- Operating System: macOS Sequoia 15.0
- Server Software Version/Commit: -

**Additional context**
The solution should be fairly straightforward, Vitepress has a documentation regarding [static assets](https://vitepress.dev/guide/asset-handling#the-public-directory), in short we can put the assets inside the `public` folder for it to be included in the build

**Comment by reynaldichernando** [comment]
I would like to submit a PR for this 🙏 .

**Comment by Snowiiii** [comment]
Hey, Really weird for my its just empty (firefox). But i also just noticed there is no favicon. You appreciate a PR. Thank you :D
![image](https://github.com/user-attachments/assets/a75f91b3-5529-4a19-b4a5-a97406c5f64e)

**Comment by reynaldichernando** [comment]
Ah, I forgot to mention that I'm on Safari, but I tried it on Chrome and it is also showing just empty.
<img width="782" alt="image" src="https://github.com/user-attachments/assets/84fb8c53-2b7d-4c58-af67-6e559524a1ee">
But the `<img>` tag is still there. I guess it is just Safari thing setting a default image.

**Comment by Snowiiii** [comment]
> Ah, I forgot to mention that I'm on Safari, but I tried it on Chrome and it is also showing just empty. <img alt="image" width="782" src="https://private-user-images.githubusercontent.com/12949382/376763562-84fb8c53-2b7d-4c58-af67-6e559524a1ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjA1ODksIm5iZiI6MTcyOTAyMDI4OSwicGF0aCI6Ii8xMjk0OTM4Mi8zNzY3NjM1NjItODRmYjhjNTMtMmI3ZC00YzU4LWFmNjctNmU1NTk1MjRhMWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE5MjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MzE2Y2E3NzA0NmM1NTFkMDI3M2UxZDE1ZjhmODBiMzU3NDViMjMzMzhlMjNiYjFhNDUyMDEwN2RlMzI1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VfXAyC1tnrpZCTNMpbTBilKQ51ss3GZFDJmwLU3i8v4"> But the `<img>` tag is still there. I guess it is just Safari thing setting a default image.

ah okay makes sense, Was thinking of that since your OS is mac.
