### ISSUE TITLE
Host docker build on a Container Registry

### ISSUE THREAD

**Issue by Legonois** [Snowiiii/Pumpkin#125]
- [x] I've searched existing issues and couldn't find a duplicate.

**Is your feature request related to a problem? Please describe.**
Using a docker image for deployment requires downloading the source code and building the image from there

**Describe the solution you'd like**
I woud like the docker builds to be published to the Github Container Registry, or any container registry by adding a github actions workflow

**Comment by Snowiiii** [comment]
Hey, Sounds like a not bad idea. But i wonder if its good to publish images every commit, Im not fimilar with docker so much but i tough this is usally done when doing releases

**Comment by Legonois** [comment]
You can run the push on release, and use the docker tagging system. Such as:

pumkin:latest
- Latest Stable Build

pumkin:nightly
- Latest Unstable Build

pumkin:x-x-x
- Specific Stable Build

pumkin:x-x-x-nightly
- Specific Unstable Build

Publishing every commit should update the pumkin:nightly build, where as when you publish releases it should be done on pumkin:latest with a corresponding pumkin:x-x-x

pumkin:x-x-x-nightly would be essentially a pre-release version of that version number

That's my idea at least. I can supply sample workflow files if you would like to see how it can be done

**Comment by Snowiiii** [comment]
Oh, This sounds cool. We currently actually already have pre-build builds. But if its also so easy to implement it for docker, sure go ahead. You may also want to take a look at: https://github.com/Snowiiii/Pumpkin/issues/132

**Comment by lokka30** [comment]
Hey @Legonois, did you plan to make a PR for this? If not, I can have a crack at it, though it might take me a while. Can only learn by trying. :)

**Comment by Snowiiii** [comment]
> Hey @Legonois, did you plan to make a PR for this? If not, I can have a crack at it, though it might take me a while. Can only learn by trying. :)

Sure, Would be great

**Comment by lokka30** [comment]
@Snowiiii would you prefer docker hub or ghcr.io?

**Comment by lokka30** [comment]
@Snowiiii said on Discord:

> i still have very limited experience with docker, You asked if i would prefer docker hub or ghcr.io. I don't know tbh. Can you may list pros and cons ?

I'm personally unaware. My assumption is that they're functionally similar for our purposes and can easily even use both simultaneously if you wanted to with only a few extra lines in the actions yaml file

Perhaps more of a deciding factor is if you have a docker account or not, which might make just using ghcr more convenient I guess.

I'll try set it up so on push to any branch it will build and deploy a docker image (notably, it's not running for people's PRs).
This is currently what I've gathered by browsing through documentation... I need to make it a smarter with what tags it assigns to the images, and others might notice other needed fixes

Please let me know what is your preference to proceed @Snowiiii. I'll continue working on #214 after confirmation

**Comment by Snowiiii** [comment]
> @Snowiiii said on Discord:
> 
> > i still have very limited experience with docker, You asked if i would prefer docker hub or ghcr.io. I don't know tbh. Can you may list pros and cons ?
> 
> I'm personally unaware. My assumption is that they're functionally similar for our purposes and can easily even use both simultaneously if you wanted to with only a few extra lines in the actions yaml file
> 
> Perhaps more of a deciding factor is if you have a docker account or not, which might make just using ghcr more convenient I guess.
> 
> I'll try set it up so on push to any branch it will build and deploy a docker image (notably, it's not running for people's PRs). This is currently what I've gathered by browsing through documentation... I need to make it a smarter with what tags it assigns to the images, and others might notice other needed fixes
> 
> Please let me know what is your preference to proceed @Snowiiii. I'll continue working on #214 after confirmation

I think using github is easier for per commit images, We may can use docker hub for release builds
