### ISSUE TITLE
[Discussion] Choice for a linear algebra library

### ISSUE THREAD

**Issue by Shyrogan** [Snowiiii/Pumpkin#127]
Hi everyone,

So far, pumpkin has in its [pumpkin-core](https://github.com/Snowiiii/Pumpkin/tree/master/pumpkin-core/src) sub project a few data structures for linear algebra such as `Vector2`, `Vector3`.

As the project evolves and takes shape, I believe it's the right moment to transition to a third-party library for these data structures, especially since such libraries are commonly used in game engines and similar projects.

Switching to a third-party library offers several benefits. It ensures we use optimized, well-tested code, reducing the chance of bugs in core operations. This also frees up development time, allowing us to focus on the unique aspects of the project rather than reinventing the wheel.

Currently, I took a look at two choices:
- [nalgebra](https://github.com/dimforge/nalgebra), a complete and very well documented linear algebra library that provides all the data structures we need in pumpkin's current state.
- [glam-rs](https://github.com/bitshifter/glam-rs), currently in beta but has a lot of potential as it provides SSE2 optimizations and third-party libraries support (for example serde or rand)

I tend to like more **glam** but I would like people to discuss and recommend other libraries if they want to.

**Comment by BGR360** [comment]
I would hardly call `glam` a beta library. Just because it's not at version 1.0 doesn't mean it's not a robust and well tested library. `glam` is the library that the extremely popular `bevy` game engine uses.

**Comment by Shyrogan** [comment]
Fair, after looking a bit at it, glam seems like a reasonable choice

**Comment by Shyrogan** [comment]
After discussing with @Snowiiii, he thinks it's over-killed and this project should rather have its own math library.
