### ISSUE TITLE
Forge/Fabric or any other modloader support?

### ISSUE THREAD

**Issue by Astronyan** [Snowiiii/Pumpkin#129]
- [x] I've searched existing issues and couldn't find a duplicate.

It's like more just a question. I want to know if there is any plans to support some mod loader to use modded minecraft server. There is?

**Comment by Snowiiii** [comment]
Hey, There are no plans to support any Java API in Rust (e.g. Fabric/Forge). However im free to add Certain Features when its Packet related (e.g. https://wiki.vg/Minecraft_Forge_Handshake)

**Comment by asodugf12** [comment]
I think it might be possible to make some kind of FFI interop between java - rust and work from there. I am not sure about performance though.
