### ISSUE TITLE
Supply `docker-compose.yml` in project

### ISSUE THREAD

**Issue by lokka30** [Snowiiii/Pumpkin#174]
- [x] I've searched existing issues and couldn't find a duplicate.

**Is your feature request related to a problem? Please describe.**
There is currently no Docker Compose file supplied with the project. I suggest supplying an example `docker-compose.yml` which can get people running with Pumpkin easily via Docker Compose.

**Describe the solution you'd like**
Ideally, we can start working on this once #125 is complete. It may be possible to do prior, using `build: .` possibly so it builds the image locally, and then switch to using the registry image once #125 is done.

**Comment by Snowiiii** [comment]
I mean yeah i was thinking of that. I don't have much experience with docker, If you like you man can try to implement #125
