### ISSUE TITLE
Make favicon loading less noisy

### ISSUE THREAD

**Issue by lokka30** [Snowiiii/Pumpkin#180]
- [x] I've searched existing issues and couldn't find a duplicate.

**Is your feature request related to a problem? Please describe.**
Pumpkin often reports two logs on startup related to the favicon:
```
2024-10-25T00:12:11.922Z INFO  [pumpkin::server::connection_cache@main] Loading server favicon from 'icon.png'
2024-10-25T00:12:11.922Z WARN  [pumpkin::server::connection_cache@main] Failed to load icon from 'icon.png': No such file or directory (os error 2)
```
In the common situation that the server admin doesn't have a favicon file (e.g., `icon.png`) to begin with, both of the above logs are verbose, and should instead be logged with the `debug` level.

**Describe the solution you'd like**
- Use `debug` log level for `Loading server favicon from...`
- If failed to load icon:
  - If error is due to the file not existing, `debug` log that the file doesn't exist
  - ...otherwise, log a warning (same exact message `failed to load icon...`), since having a working favicon was likely intentional

Code location: `connection_cache.rs`, in function `build_response(config: &BasicConfiguration)`

Happy to work on this if you're interested.

**Comment by Snowiiii** [comment]
> Did you want the second message hidden if it's file not found? Or perhaps even better we can make the icon disabled by default in the configuration so the logic only runs when the server owner intends it to

I would like to no having it as an error. Im fine with something like "icon.png not found, Using Default icon"
