### ISSUE TITLE
Handle SIGTERM on UNIX

### ISSUE THREAD

**Issue by lokka30** [Snowiiii/Pumpkin#182]
- [x] I've searched existing issues and couldn't find a duplicate.

**Is your feature request related to a problem? Please describe.**
- Pumpkin currently handles `SIGINT` via `ctrlc::set_handler` in `main.rs`, however, it doesn't handle `SIGTERM`
- Handling `SIGTERM` is especially important for Docker, since it will allow Docker to gracefully stop the server, instead of killing it.

**Describe the solution you'd like**
- The `ctrlc` crate we are are already using can simply have its `termination` feature enabled in `cargo.toml` with no other changes required.
- Whilst working on this, may as well also comment the ctrlc part of the `main` function more, and use `expect` instead of `unwrap` for a better error message if unsuccessful.
- To my understanding, these changes do not create any caveats for OS compatibility, i.e., non-UNIX.

**Comment by Snowiiii** [comment]
Hey @lokka30, Good idea. But i actually just discovered that tokio has signal handling as well. Its a feature and the docs can be found at https://docs.rs/tokio/latest/tokio/signal/index.html. It can handle everything we need ctrlc, sigterm, sighup. It would be cool if we could drop a crate we don't need then :D.

**Comment by lokka30** [comment]
Awesome, i'll get working on this! I did notice this actually before stumbling upon our ctrlc code. I'll need to double check the tokio stuff will work on non-unix platforms (i.e., just ignore the incompatible signal registrations on non-unix systems).

**Comment by lokka30** [comment]
Would you like me to make a new PR, or just add another commit to this and it will be squash merged?

**Comment by Snowiiii** [comment]
> Would you like me to make a new PR, or just add another commit to this and it will be squash merged?

Im fine if you make it in the same PR
