### ISSUE TITLE
Server trying to kick a client with a closed connection, when the connection shouldnt be closed

### ISSUE THREAD

**Issue by AnonymousBit0111** [Snowiiii/Pumpkin#184]
- [x] I've searched existing issues and couldn't find a duplicate.

The server is trying to kick me while I'm still in the world and then it panics here https://github.com/AnonymousBit0111/Pumpkin/blob/master/pumpkin/src/entity/player.rs#L290-L300
note: on my fork I've changed it from asserting to just logging so that the server doesn't stop when this happens so I can investigate a bit better.

**To Reproduce**
simply join the server and fly around for a minute or so

**Expected behavior**
a client only gets kicked if there's a timeout of for some other valid reason

**Environment (please complete the following information):**

- Operating System: MacOS ventura
- Server Software Version/Commit: e1fa2b7c69198461cbf44728816f4e8d60047732

**Comment by kralverde** [comment]
Fixed in https://github.com/Snowiiii/Pumpkin/pull/172
