### ISSUE TITLE
Worldborder Doesn't Check for Negatives

### ISSUE THREAD

**Issue by DirefulBelt6803** [Snowiiii/Pumpkin#210]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Arch Linux

### Server Software Version/Commit

79d2f91

### What happened?

Worldborder command can be executed using negative numbers, which can cause the player to be kicked from the game and unable to rejoin. Vanilla minecraft doesn't allow a worldborder less one.

### To Reproduce

/worldborder set -1000

### Expected behavior

log syntax error "Worldborder cannot be smaller than 1 block wide"

**Comment by suprohub** [comment]
Just add checking > 0

**Comment by Snowiiii** [comment]
I was thinking of adding 3 argument consumers. 
1. only negative numbers. 
2. positive and negative numbers.
3. only positive numbers

This should make Command creation for us and future Plugin maintainers easier

**Comment by Alvsch** [comment]
I think a  `BoundedNumberConsumer<f64>`, or something in that direction would be more flexible.
