### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by suprohub** [Snowiiii/Pumpkin#213]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Arch linux

### Server Software Version/Commit

latest

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

What about creating organization? because the project is getting bigger and more people are working on itю

**Comment by Snowiiii** [comment]
I don't think there is a need for an Organization, Some people already asked me, But i don't really see the Point.

**Comment by Snowiiii** [comment]
Currently i see no problems and i like how it is
