### ISSUE TITLE
Version selector

### ISSUE THREAD

**Issue by JerimiahOfficial** [Snowiiii/Pumpkin#223]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

I understand that the project supports the latest Minecraft server version. But is there plans to support older versions?

### Describe the solution you'd like

Inside of the `configuration.toml` you could specify a certain version of Minecraft for the server. Based off of that it would select the server api for that version.

**Comment by suprohub** [comment]
I think itz be nod bad if we just create new branch on new version

**Comment by Snowiiii** [comment]
Supporting multiple Minecraft version is very hard. It also forces to main old legacy code. Pumpkin aims to support the latest Minecraft version and port to a new Version when there is a new release from Mojang. Every Pumpkin release will be taged with a Branch Tag but its not planned to maintain older Pumpkin versions

**Comment by suprohub** [comment]
> Tag
Maintain can be needed to fix security issues, but fix all issues - yeah its very hard

**Comment by JerimiahOfficial** [comment]
> Supporting multiple Minecraft version is very hard. It also forces to main old legacy code. Pumpkin aims to support the latest Minecraft version and port to a new Version when there is a new release from Mojang. Every Pumpkin release will be taged with a Branch Tag but its not planned to maintain older Pumpkin versions

Okay good to know.
