### ISSUE TITLE
Server autorestart

### ISSUE THREAD

**Issue by suprohub** [Snowiiii/Pumpkin#225]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

Server not restarts

### Describe the solution you'd like

In my pr i separsted logic for server start and launching console ui.
So if pr is merget after that we can add autorestart in config. What do you think?

**Comment by ismaildasci** [comment]
Hey! 👋

Thanks for the suggestion and for working on this PR! Separating the logic for starting the server and launching the console UI sounds like a good step. It would definitely make it easier to implement features like auto-restart without affecting the UI.

Just to clarify:

    Would the auto-restart option in the config apply to all environments, or would it be customizable per environment (e.g., only in development)?
    How would this handle errors during restart? For instance, would there be a limit to the number of restart attempts?

These details could help ensure a smooth integration. Let us know your thoughts! 😊

**Comment by iamnoksio** [comment]
Imo auto restart should be a plugin and not a built-in mechanic
