### ISSUE TITLE
Server Templates

### ISSUE THREAD

**Issue by suprohub** [Snowiiii/Pumpkin#226]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

Only vanilla implementation

### Describe the solution you'd like

How do you thibk about server tenplates?
Like vanilla, minigames, pvp or none?
Its like a very very basic plugin for setup world rules and other

**Comment by suprohub** [comment]
I mean like write
template = "vanilla"
or template = "buildserver"
Instead of
allowpvp = false
gamemode = "creatuve"
etc

**Comment by suprohub** [comment]
Create some very basic configs

**Comment by Snowiiii** [comment]
I still don't really understand what you mean by Templates, Pumpkin can be really customizable, people can may create Configs to be optimal for certain game modes

**Comment by Snowiiii** [comment]
Pumpkin is not made to have build-in minigames or something like that. If anyone wants to provide configs or plugins for certain minigames no one stops them
