### ISSUE TITLE
Infinite block placing + incorrect block placing

### ISSUE THREAD

**Issue by enthermo** [Snowiiii/Pumpkin#230]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Windows 11, Minecraft Version 1.21.3 (Latest)

### Server Software Version/Commit

87aa5ec

### What happened?

The server copies the first placed block by the player and infinitely places it, regardless of what the player has in their hand or if they have enough of that item to place. This works with an empty inventory and in survival.

I have seen the server be 'fine' for ~15 seconds and then remove all blocks (regen the chunk?) and then do this bug. Clearly the server is preserving the first block the player interacts with and not updating, should be an easy fix.

### To Reproduce

```
git clone (this repo)
cargo build -r
cargo run -r
```
Join server running on localhost, use the server console to change gamemode to creative and add blocks to inventory. Place any block, then switch to a different block. The first placed block will be placed instead of the selected block.

### Expected behavior

The server should verify if the player has an item in hand and place the appropriate block.

**Comment by enthermo** [comment]
Found the issue [here](https://github.com/Snowiiii/Pumpkin/blob/87aa5ec49305b7fdafc2e737cd18a6cee24f5403/pumpkin/src/client/player_packet.rs#L592). When set `item_allowed_override` is set to false the server behaves normally. Leaving this issue open as this is likely not intended behavior.

**Comment by Snowiiii** [comment]
Currently the item count is not decreased when a block is being placed by a player in survival mode. I will take a look on this tomorrow
