### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by Polygons1** [Snowiiii/Pumpkin#247]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

macOS Sonoma

### Server Software Version/Commit

Public Server

### What happened?

1. can't edit / write on signs
2. grass can float
3. connection timed out when the player in 29,999,999 ~ 29,999,999 (and can't log back on)

### To Reproduce

1. place a sign, no gui will appear
2. break block underneath grass
3. teleport to 29,999,999 29,999,999 (x, z)

### Expected behavior

1. gui to appear
2. grass to be broken
3. allow joining back and connection not timing out

**Comment by Snowiiii** [comment]
All bugs besides sign editing are fixed. I recommend opening one issue for every bug/feature instead of reporting multiple bugs or missing features in one issue
