### ISSUE TITLE
Cache rust dependencies for GitHub repo workflows

### ISSUE THREAD

**Issue by lokka30** [Snowiiii/Pumpkin#248]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

GitHub action workflows take a while for Pumpkin because it has to recompile all of its dependencies every time it runs. If these dependencies are cached, actions should run quicker.

### Describe the solution you'd like

An interesting implementation is demonstrated [here](https://www.uffizzi.com/blog/optimizing-rust-builds-for-faster-github-actions-pipelines).

**Comment by Snowiiii** [comment]
Sounds like a good idea, I was already thinking of adding that

**Comment by Snowiiii** [comment]
I think https://github.com/Snowiiii/Pumpkin/commit/0ab4b5daed9515de85db10c4f33080895f980d05 should resolve this issue
