### ISSUE TITLE
Player flying in survival mode

### ISSUE THREAD

**Issue by Rotstein007** [Snowiiii/Pumpkin#278]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Linux manjaro

### Server Software Version/Commit

public server

### What happened?

If you join the server, you are in survival mode by default. As long as you don't change your gamemode, you're able to fly through the world. If you do change your gamemode and switch back to survival, you're unable to fly, as it should be.

### To Reproduce

switch to creative and back to survival

### Expected behavior

If the player is in survival mode, he shouldn't be able to fly.

**Comment by DataM0del** [comment]
I already opened a PR for fixing that, it was just some leftover debug code.
