### ISSUE TITLE
The player's 2nd skinof his skin and cape didn't appear after /kill

### ISSUE THREAD

**Issue by hthug06** [Snowiiii/Pumpkin#284]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Windows 11

### Server Software Version/Commit

29d203c

### What happened?

When the player use /kill and respawn, The second layer of his skin and is cape does not appear.
Before /kill:
![image](https://github.com/user-attachments/assets/a4aa7467-8d32-4bc4-88ac-de7f12263075)

After /kill:
![image](https://github.com/user-attachments/assets/4bcba7a4-7269-4f3d-9a5c-0dd91081ddde)

(all the settings in Skin Customization are ON)

### To Reproduce

use /kill and respawn

### Expected behavior

Player skin to be like before the /kill

**Comment by Snowiiii** [comment]
Fixed in https://github.com/Snowiiii/Pumpkin/pull/300
