### ISSUE TITLE
Falling through world

### ISSUE THREAD

**Issue by Commandcracker** [Snowiiii/Pumpkin#286]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Windows 11

### Server Software Version/Commit

29d203c8a9899ed9e9e6b147f79d67bc7feca504

### What happened?

I'm **consistently** falling through the world when I join and I when I respawn I'm still 1 inside a block.
Must be some coalition calculation issue.

Maybe also threading because I have 32 core.

https://github.com/user-attachments/assets/2e592645-73c0-4523-9c07-b330be9c0ee1

### To Reproduce

IDK

### Expected behavior

Not falling through the World :D

**Comment by Commandcracker** [comment]
Only happens in debug build tho 🤔

**Comment by DataM0del** [comment]
Also, sometimes it spawns you 2 or 1 block(s) inside the ground.

**Comment by DataM0del** [comment]
> An in release, it sometimes works as intended 🤔

I think it's because the chunk generation or something is faster and makes it so you don't fall because the client hasn't gotten a chunk yet and is assuming all air.
