### ISSUE TITLE
Decompiler script uses overly specific version of Python

### ISSUE THREAD

**Issue by sachharine** [Snowiiii/Pumpkin#29]
decompile.sh attempts to call "python3.12" to run DecompilerMC which only requires Python 3.7+ according to its README, and as such will take extra effort to run on systems where Python 3.12 is not packaged.

**Comment by Snowiiii** [comment]
Hey, Thanks for the issue. I just changed it at https://github.com/Snowiiii/Pumpkin/commit/3579b9ccde990117da3dca252928376147bdcdc6

**Comment by sachharine** [comment]
Ah, but the script still calls Python 3.12, see https://github.com/Snowiiii/Pumpkin/blob/master/mc-source-code/decompile.sh#L24.

**Comment by Snowiiii** [comment]
My bad. I think i now should be fixed https://github.com/Snowiiii/Pumpkin/commit/2eb4c8624fcadbb6461288d103ed8828a521b9ed

**Comment by sachharine** [comment]
Great, closing. Thank you for the quick resolution.
