### ISSUE TITLE
Extract block hardness in block extractor

### ISSUE THREAD

**Issue by user622628252416** [Snowiiii/Pumpkin#297]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

Block hardness is required for calculating block breaking speed, which is needed to determine whether a block was broken instantly or the breaking was cancelled, as the client does not send a breaking finished packet when a block was broken instantly, even in survival mode.

### Describe the solution you'd like

block hardness should be extracted and added to blocks.json

**Comment by user622628252416** [comment]
While you're at it, wheter a player can stand on a block should also be extracted. That's required for get_top_block for example

**Comment by Snowiiii** [comment]
> While you're at it, whether a player can stand on a block should also be extracted. That's required for getting the top block when spawning players for example, currently that just checks whether a block is air

Im not sure what do you mean by "whether a player can stand on a block"

**Comment by user622628252416** [comment]
> > While you're at it, whether a player can stand on a block should also be extracted. That's required for getting the top block when spawning players for example, currently that just checks whether a block is air
> 
> Im not sure what do you mean by "whether a player can stand on a block"

What I meant was whether the block has a collision shape, but now that I think about it that doesn't make much sense, as collisions are a lot more complex than that. I also didn't realize before that there are in fact already collision shapes in blocks.json, so sorry for not doing my due diligence and thanks for adding block hardness!
