### ISSUE TITLE
Server crashes when player joins

### ISSUE THREAD

**Issue by NGSpace** [Snowiiii/Pumpkin#30]
![image](https://github.com/user-attachments/assets/f103f95a-cd37-4cb1-b03d-bb1d5423e2ba)

This is Latest commit, without the "--release" tag as running with the "--release" tag takes a while to load before putting me into a blank world even after copying a world from my .minecraft folder to the server (and renaming it to "world")

**Comment by zp3x** [comment]
It looks like your world has not enough chunks generated.

**Comment by NGSpace** [comment]
What is the recommended amount of chunks?

**Comment by lukas0008** [comment]
Make sure to load at least the chunks around (0,0), by default Minecraft spawns you close by, but usually not close enough to have them generated. Also I'd recommend if you pulled the latest changes, since the chunk loading got a lot faster.

**Comment by NGSpace** [comment]
![image](https://github.com/user-attachments/assets/783b83ab-4902-4f42-bba3-cdf4b012424d)
They say Java error messages are unreadable... This is without the release tag... My client crashed shortly after but idk if that's related.

**Comment by lukas0008** [comment]
Oh this is most likely because of spigot, currently we are loading the worlds the way that vanilla does it. I plan to make it work with the bukkit file structure as well, but for now it is not supported. You can also just generate a single player file, drag it from `.minecraft/saves/` to `Pumpkin/` and rename it to `world`.

**Comment by NGSpace** [comment]
That's exactly what I did...

**Comment by lukas0008** [comment]
That seems weird, check if inside of your `world/` folder there is a `region/` folder, and a file called `r.0.0.mca`.
Also try running this with the `--release` flag, then even if the world does not load, it should not crash.

**Comment by NGSpace** [comment]
![image](https://github.com/user-attachments/assets/6b2dda9a-a812-4f42-81e2-04008c9b078c)

with the release flag it doesn't crash but it doesn't show anything either...

**Comment by lukas0008** [comment]
did you put `world/` inside `Pumpkin/` or `Pumpkin/pumpkin/`?

**Comment by NGSpace** [comment]
I just checked and apparently I accidentally put it in one of the random folders... ops...
