### ISSUE TITLE
Rename master to main ?

### ISSUE THREAD

**Issue by Commandcracker** [Snowiiii/Pumpkin#317]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

See https://sfconservancy.org/news/2020/jun/23/gitbranchname/
My thought is, if you want to change it, better do it now, then later on.

### Describe the solution you'd like

Rename master to main.

**Comment by Snowiiii** [comment]
I see no reason to name it main

**Comment by Commandcracker** [comment]
Just wanted to ask because some projects do it later on and then something breaks.
Btw, I personally don't care what the central branch is called, just don't call it "zentraler-git-zweig"
