### ISSUE TITLE
Very slow(32.09s) connection times

### ISSUE THREAD

**Issue by FractalFir** [Snowiiii/Pumpkin#33]
Hi! I have recently discovered your project, and wanted to check it out.

However, when I tried to run it, I have discovered that connecting to the server took a shocking amount of time - over 32 seconds! 

So, I decided to investigate. 

When I run pumpkin under a profiler(samply), I can clearly see that it spends most of the time doing... nothing. 

![Screenshot from 2024-08-19 02-26-40](https://github.com/user-attachments/assets/f53895d3-4460-4083-8ca1-4be99cbc7e7e)

The CPU activity is represented using the yellow colour. As you can clearly see, pumpkin does nothing most of the time. 

This is quite strange, but it looks to me like Pumpkin is spending most of its time outside user space - presumably performing syscalls(?). 

After looking around for a bit more, it seems like Pumpkin only processes events once per second (at least when I run it), which prevents it from connecting the player faster. 

After a bit more digging, I have discovered Pumpkin spends most of its time waiting for events in [main](https://github.com/Snowiiii/Pumpkin/blob/77b205ada0c87f0c5608d37517d832792afde622/pumpkin/src/main.rs#L105).

The documentation of [mio::Pool::pool](https://docs.rs/mio/latest/mio/struct.Poll.html#method.poll) says that it is a blocking function, so that maybe could be the cause(?).

I am not sure if this is intentional, or if it is something that occurs on other OSs.

**Comment by Snowiiii** [comment]
Hey, This is definitly not normal and i never had that problem is the past. Thanks for your investigations so far. I will take a look myself when i have time

**Comment by FractalFir** [comment]
After looking into things more, this issue only seems to occur if no pregenerated chunks are present. If a minecraft world is present, then pumpkin loads very fast.

**Comment by Snowiiii** [comment]
Ah. Makes sense then. I really need to build a panic for now when no world is added

**Comment by Snowiiii** [comment]
Okay, We now check if the world exists and if not panic. This will let everyone know that they have to use an world. Can we close this?

https://github.com/Snowiiii/Pumpkin/commit/222b40c8bdcb9d760e387fd432347fdc5c319aa8

**Comment by FractalFir** [comment]
Yeah. I would prefer if Pumpkin autogenerated a super flat world if there is no world, but this solution is OK too.

**Comment by Snowiiii** [comment]
> Yeah. I would prefer if Pumpkin autogenerated a super flat world if there is no world, but this solution is OK too. I can now connect to a world no problem.

It will generate Worlds if there are none. When we have world generation
