### ISSUE TITLE
player in creative does not fly after /kill

### ISSUE THREAD

**Issue by sayak111** [Snowiiii/Pumpkin#367]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

windows 10

### Server Software Version/Commit

IDK I just used pumpkin.kralverde.dev

### What happened?

I did /kill in creative to myself and then it didn't allow me to fly.
I tried to change to adventure mode  and back and then it let my fly but at super speed

### To Reproduce

/kill in creative and then try to fly after that.

### Expected behavior

to fly in the normal speed all the time no matter what 
and be able to fly after /kill in creative.

**Comment by Commandcracker** [comment]
Probably because change game mode is not changing the player abilities, ill have a look soon.
