### ISSUE TITLE
Block <id> does not exist

### ISSUE THREAD

**Issue by Commandcracker** [Snowiiii/Pumpkin#375]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Windows

### Server Software Version/Commit

0.1.0-dev e26ffae-m

### What happened?

![image](https://github.com/user-attachments/assets/85a0a55f-56bd-4b86-8f00-ccdf95faff2c)
all block IDs do not exist

### To Reproduce

run /fill or /setblock

### Expected behavior

Existing block IDs :D

**Comment by DataM0del** [comment]
> ### I've searched existing issues and couldn't find a duplicate.
> 
>     * [x]  I confirm this is not a duplicate.
> 
> 
> ### Operating System
> 
> Windows
> ### Server Software Version/Commit
> 
> 0.1.0-dev [e26ffae](https://github.com/Snowiiii/Pumpkin/commit/e26ffae8430e173a8b05b6b6a457b5a144b04ee2)-m
> ### What happened?
> 
> ![image](https://private-user-images.githubusercontent.com/49335821/392588922-85a0a55f-56bd-4b86-8f00-ccdf95faff2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1ODAzNzEsIm5iZiI6MTczMzU4MDA3MSwicGF0aCI6Ii80OTMzNTgyMS8zOTI1ODg5MjItODVhMGE1NWYtNTZiZC00Yjg2LThmMDAtY2NkZjk1ZmFmZjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDE0MDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZDk2ZDRiOTEyNjkyMDFmNDIyNTIxODk4MjlhZTg5OGIwMTA1YmM5M2I0OWNkZjA3MTFjMzUwNzgwNTBmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DLXHI6wDg2Q0L72QPYz-x4zia6axkMpzADj4MqZ3Z2Y) all block IDs do not exist
> ### To Reproduce
> 
> run /fill or /setblock
> ### Expected behavior
> 
> Existing block IDs :D

What if you delete the `minecraft` prefix? Would that change anything?

**Comment by Snowiiii** [comment]
Weird. Give command works normally its only fill
