### ISSUE TITLE
Exited Code 132

### ISSUE THREAD

**Issue by technoman555** [Snowiiii/Pumpkin#408]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Docker Cluster on Ubuntu 24.04

### Server Software Version/Commit

ghcr.io/snowiiii/pumpkin:master

### What happened?

Using Docker, my Docker cluster, I pulled the most recent master image and spun up a container. I then logged in using the publicly assigned IP address. I was kicked one but the log only shows an accepted connection. no other errors. I login again and the server allows me in I disconnect and now the server refuses to connect and crashes with exited Code 132

### To Reproduce

If you need me to host the server so you can see this problem, I'd be happy to, as I haven't had this happen on my local network, so I'm not sure what the underlying issue may be as of yet.

### Expected behavior

The server should allow players to log in without any connection issues or the server crashes with no errors recorded.

**Comment by technoman555** [comment]
Correction to this connecting to the image from docker either over Local or Public server breaks and exits the server with the same error code.

**Comment by Yimura** [comment]
I just encountered this same issue on my server by using the container image from `ghcr.io/snowiiii/pumpkin:master`.

Exit code `132` seems to imply the container attempted to execute an illegal instruction, my guess is that the following happened.
Github's Action Runners have CPU's with quite a lot of instruction sets available which not everyone may have, one of the modules/packages in Pumpkin is making use of this unusual instruction.

One temporary solution ofcourse is to clone the repository locally and then deploy it from there however that may be a few steps too many for some that'd rather just pull it straight from the Github registry.

**Comment by Snowiiii** [comment]
Can you please test again after the latest commit
https://github.com/Snowiiii/Pumpkin/commit/febbfd89e6c647f11612721c3f8a1b4cc7fad9cc

**Comment by technoman555** [comment]
Issues are resolved. Docker seems to not throw exited code 132 anymore after testing. Both locally and on cluster production servers.
