### ISSUE TITLE
Ranks system in config for permissions

### ISSUE THREAD

**Issue by glitchy-sk8k9** [Snowiiii/Pumpkin#411]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

no it's QoL, just a suggestion

### Describe the solution you'd like

Basically a config file where you could define ranks and ranks would have permission nodes, kinda like luckperms or powerranks

**Comment by Commandcracker** [comment]
See #35, this is a duplicate.
We will probably be using SQLite as default and add an option to change the storage method later on.
(A "config file" is not suited for a large amount of permissions)

**Comment by glitchy-sk8k9** [comment]
Sorry for being dumb!
