### ISSUE TITLE
Mousewheel click to get item / get scrolled to an item

### ISSUE THREAD

**Issue by Rotstein007** [Snowiiii/Pumpkin#413]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Is your feature request related to a problem? Please describe.

Mouswheel click is not implementet yet.

### Describe the solution you'd like

In Vanilla, when you do an mousewheel click to an block, you get this block in your hand like /give if you don't have it in your inventory. If you have it in a different hand slot, your selection gets set to this block. If you have it in your inventory, it get moved in your hand slot and if your hand slot is blocked with another block, that it get swapped with that.

**Comment by Bafran** [comment]
I believe this may be a duplicate of issue #397

**Comment by Rotstein007** [comment]
Sorry,
i searched for Mousewheel and select and didn't find anything. My fault.
