### ISSUE TITLE
Quick start guide down

### ISSUE THREAD

**Issue by Tunga-Tech** [Snowiiii/Pumpkin#416]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

any

### Server Software Version/Commit

not applicable

### What happened?

The quick start guide link on the main repository takes you to the old website address causing github pages to give a 404 error.

### To Reproduce

Go to the quick start link.

### Expected behavior

for it to take you to the quick start guide.

**Comment by DataM0del** [comment]
@Tunga-Tech The button works, probably fixed already, so close the issue.
