### ISSUE TITLE
decompile.sh broken

### ISSUE THREAD

**Issue by DaniD3v** [Snowiiii/Pumpkin#46]
@ferdinandkeller 

- `#!/bin/bash` is not Posix compliant. Use `#!/bin/env bash` or `#!/bin/sh`.
You're not using any bash specific stuff anyways so I'd go with `#!/bin/sh`
- No `set -eu` which means commands like `cd` can silently fail
- `rm -r DecompilerMC` doesn't work non-interactively because git has write-protected files. do `rm -rf` instead 
- Script copies `pom.xml` and cd's into directory for seemingly no reason. It ends with comment `#mvn clean install`?
- Unreasonable amount of default flags set when launching the DecompilerMC script.
- `cd ../src/$MC_VERSION/server` is not the directory you wanted to cd because into it doesn't exist.
This fails silently without `set -eu`, which is why you didn't notice.

I would've fixed this myself but I have no clue what the `#mvn clean install` is supposed to do (I don't use java a lot, never used maven).
Here's the part that I could fix myself

```sh
#!/bin/sh
set -eu

# This script decompiles the official Minecraft server JAR file.
# Be careful, as releasing the decompiled source code is against Minecraft's EULA.

# configure which version we want to decompile
MC_VERSION="1.21"

# remove folders if they already exist
if [ -d "DecompilerMC" ]; then rm -rf DecompilerMC; fi
if [ -d "src" ]; then rm -r src; fi
if [ -d "target" ]; then rm -r target; fi

# clone DecompilerMC for automatic decompilation
# look here for more informations:
# - https://minecraft.fandom.com/wiki/Tutorials/See_Minecraft%27s_code
# - https://github.com/hube12/DecompilerMC
git clone https://github.com/hube12/DecompilerMC.git -q
echo "DecompilerMC cloned successfully."

cd DecompilerMC

# decompile the server JAR file
echo "Decompilation might take a while, please be patient."
python3 main.py --mcversion $MC_VERSION --side server -q

# move it to the correct directory
mv src ..
cd ..

echo "$PWD"

# move the custom made pom.xml
cp pom.xml src/$MC_VERSION/server

# install the dependencies
cd src/$MC_VERSION/server
# mvn clean install
```

**Comment by Snowiiii** [comment]
I wonder if this even is a good idea to include this in the project. There are many easy to use MC Decompilers out there. I also see that many people get confused when they see the folder name and think that we include the offical source code which is totally illegal

**Comment by ferdinandkeller** [comment]
We can remove it if it makes things simpler.
