### ISSUE TITLE
Usage of Arc<usize>

### ISSUE THREAD

**Issue by user622628252416** [Snowiiii/Pumpkin#62]
Specifically in server.rs `Server`'s `current_players` is a `HashMap<Arc<Token>, Arc<Mutex<Player>>>`, where according to the docs `Token` is just a wrapper around `usize`. It even implements `Copy`. I just wanted to ask whether this has a purpose because it seemed a bit odd to me and I'm not sure whether I'm missing something.

**Comment by Snowiiii** [comment]
It does actually not really make a difference, I may also considered to use an UUID but use an Token is easier because we can just reuse them from the clients

**Comment by Snowiiii** [comment]
btw. Are your in our discord?. It would be cool if we could exchange ideas

**Comment by lukas0008** [comment]
@Snowiiii The issue here is that cloning Arc<Token> is much more expensive than Token, and it also has a larger memory footprint.

**Comment by Snowiiii** [comment]
Resolved in https://github.com/Snowiiii/Pumpkin/pull/74
