### ISSUE TITLE
Add Basic Lighting

### ISSUE THREAD

**Issue by Snowiiii** [Snowiiii/Pumpkin#93]
Add Basic Chunk lighting. Chunk lighting is calculated on the Server. The light value reaches between 0 to 15

@lukas0008 is currently partially working on. But he is slow ngl

**Comment by lukas0008** [comment]
If someone else wants to work on this rn then please say it here, or @ me in the discord, I'm not working on lighting atm, but when i want to continue in the future, i dont want to do so if someone already is doing it.

**Comment by Snowiiii** [comment]
Thanks again to @EamonHeffernan for adding basic lightning
