### ISSUE TITLE
Add tab support for commands

### ISSUE THREAD

**Issue by Snowiiii** [Snowiiii/Pumpkin#94]
Support Name Tabing when writing Commands. We want to add Support for both Console and In-Game

## Game Packets
- [x] https://wiki.vg/Protocol#Command_Suggestions_Response
- [x] https://wiki.vg/Protocol#Commands (Optional i think)

**Comment by wendulem** [comment]
@Snowiiii Hey, first time contributor. Could you document this a bit more. Do you mean that when processing stdin in main.rs the command dispatcher (given the user pressed tab) should output the command names that match - or complete stdin with the uniquely matching command in that case

**Comment by Snowiiii** [comment]
> @Snowiiii Hey, first time contributor. Could you document this a bit more. Do you mean that when processing stdin in main.rs the command dispatcher (given the user pressed tab) should output the command names that match - or complete stdin with the uniquely matching command in that case

Hey, Great your interested in contributing. Pumpkin is currently heavily in WIP. That's the Reason documentation is so poor. I also opend this issue recently and completely forgot about it. I will edit it a bit to give more Informations.

So the Plan is to support both Tab support in the Server Console and In-Game.

We have a Command Dispatcher struct which is stored in `pumpkin/server.rs`. The Dispatcher has all Command

**Comment by marc-marcos** [comment]
If @Snowiiii isn't actively working on it I would like to give it a try!

**Comment by Snowiiii** [comment]
> If @Snowiiii isn't actively working on it I would like to give it a try!

No, Problem. go ahead

**Comment by user622628252416** [comment]
@marc-marcos Hi, are you still working on this? Else I'd pick this up

**Comment by marc-marcos** [comment]
Go for it!
